# Generated by Django 5.1.1 on 2024-10-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='decription',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=280, null=True),
        ),
    ]
