# Generated by Django 5.1.1 on 2024-10-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_post_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Dp',
            field=models.ImageField(default='defaultdp.jpeg ', upload_to='media/'),
        ),
    ]
