# Generated by Django 5.1.1 on 2024-11-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_post_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Dp',
        ),
    ]
